# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_details(object):
    def setupUi(self, details):
        details.setObjectName("details")
        details.resize(560, 723)
        self.verticalLayout = QtWidgets.QVBoxLayout(details)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(details)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.hLayout = QtWidgets.QHBoxLayout()
        self.hLayout.setObjectName("hLayout")
        self.cbCommand = QtWidgets.QComboBox(details)
        self.cbCommand.setObjectName("cbCommand")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.cbCommand.addItem("")
        self.hLayout.addWidget(self.cbCommand)
        self.dsValue = QtWidgets.QDoubleSpinBox(details)
        self.dsValue.setObjectName("dsValue")
        self.hLayout.addWidget(self.dsValue)
        self.pbSend = QtWidgets.QPushButton(details)
        self.pbSend.setObjectName("pbSend")
        self.hLayout.addWidget(self.pbSend)
        self.verticalLayout.addLayout(self.hLayout)

        self.retranslateUi(details)
        QtCore.QMetaObject.connectSlotsByName(details)

    def retranslateUi(self, details):
        _translate = QtCore.QCoreApplication.translate
        details.setWindowTitle(_translate("details", "Form"))
        self.cbCommand.setItemText(0, _translate("details", "Volume", "0"))
        self.cbCommand.setItemText(1, _translate("details", "McCready", "1"))
        self.cbCommand.setItemText(2, _translate("details", "Water Ballast", "2"))
        self.cbCommand.setItemText(3, _translate("details", "Bugs", "3"))
        self.cbCommand.setItemText(4, _translate("details", "QNH", "4"))
        self.cbCommand.setItemText(5, _translate("details", "Pilot Weight", "5"))
        self.cbCommand.setItemText(6, _translate("details", "TC Climb Rate", "7"))
        self.cbCommand.setItemText(7, _translate("details", "TC Speed To Fly", "8"))
        self.cbCommand.setItemText(8, _translate("details", "Speed To Fly / Vario", "9"))
        self.pbSend.setText(_translate("details", "Send via Can"))
